print(' ' * 9, 'a')
print(' ' * 8, 'a' * 3)
print(' ' * 7, 'a' * 5)
print(' ' * 6, 'a' * 7)
print(' ' * 5, 'a' * 9)
print(' ' * 4, 'a' * 11)
print(' ' * 3, 'a' * 13)
print(' ' * 2, 'a' * 15)
print(' ' * 1, 'a' * 17)
print(' ' * 0, 'a' * 19)
print(' ')
print(' ' * 0, 'a' * 19)
print(' ' * 1, 'a' * 17)
print(' ' * 2, 'a' * 15)
print(' ' * 3, 'a' * 13)
print(' ' * 4, 'a' * 11)
print(' ' * 5, 'a' * 9)
print(' ' * 6, 'a' * 7)
print(' ' * 7, 'a' * 5)
print(' ' * 8, 'a' * 3)
print(' ' * 9, 'a')
